name: Build & Test ObjectPool (CMake)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # -----------------------------------------------------
    # Install dependencies: g++-14, Ninja
    # -----------------------------------------------------
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-14 ninja-build
        cmake --version
        g++ --version

    # -----------------------------------------------------
    # Configure (CMake build system generation)
    # -----------------------------------------------------
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build \
                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                 -G Ninja

    # -----------------------------------------------------
    # Build
    # -----------------------------------------------------
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # -----------------------------------------------------
    # Test
    # -----------------------------------------------------
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

